### PR TITLE
Allow relative condition module names

### LINKED ISSUE #33: Boolean Conditional is not working
a import like
`require('~/modules/notice-box#?triwala-vk/modules/notice-box-exists');`
where `triwala-vk/modules/notice-box-exists` is the module that exports a boolean does not work.

a error is thrown `Condition modules cannot contain . or / in the name`
https://github.com/stealjs/steal-conditional/blob/master/conditional.js#L58

@m-mujica do you know why `.` and `/` is forbidden?

### PR DESCRIPTION
**Pull request by m-mujica**
Closes #33

### CODE REVIEW

**Comment by m-mujica** [comment]
@matthewp I moved the tests from the steal branch here, also since I'm not a fan of the `makeIframe` thing I found `qunit-composite` it's a little bit noisy but works fine 

https://travis-ci.org/stealjs/steal-conditional/builds/208778047#L355-L369

**Comment by m-mujica** [comment]
I ran steal-tools tests against this branch, looking good https://github.com/stealjs/steal-tools/pull/621

**Comment by matthewp** [comment]
Ah, composite looks quite nice!

**Comment by matthewp** [comment]
Ready to release.

1q3gh9j

**Pull request merged**
